### ISSUE TITLE
Explore open datasets of geographic borders (countries, states, cities)

### ISSUE THREAD

**Issue by zerefwayne** [JuliaGeo/GADM.jl#1]

**Comment by zerefwayne** [comment]
Resource for obtaining **country** boundaries (4MB size)

:warning: Size is large
:heavy_check_mark: Very detailed

[https://data.world/dgreiner/world-spatial-data/file/ne_50m_admin_0_countries.geojson](https://data.world/dgreiner/world-spatial-data/file/ne_50m_admin_0_countries.geojson)

![image](https://user-images.githubusercontent.com/28949397/96860901-fabd2000-1480-11eb-882a-5e7e1ada902b.png)

**Comment by zerefwayne** [comment]
Resource for **country** boundaries (250KB)

:heavy_check_mark: Size is manageable
:warning: Might lack details

[https://github.com/johan/world.geo.json/blob/master/countries.geo.json](https://github.com/johan/world.geo.json/blob/master/countries.geo.json)

![image](https://user-images.githubusercontent.com/28949397/96861028-24764700-1481-11eb-9602-9ae899ba93f2.png)

**Comment by juliohm** [comment]
Based on our discussion in Zulip, it seems that we have a comprehensive dataset by GADM that we could use via DataDeps.jl

I've looked into the other data sources you shared in the docs folder, and only two of them seem reliable:

- https://www.naturalearthdata.com/downloads/10m-cultural-vectors
- https://data.world/dgreiner/world-spatial-data

Where the second is the same as the first but in GeoJSON as opposed to Shapefile. Let's aim our initial efforts with GADM as you suggested. I've noticed that they provide URLs for each country and recommend to download the dataset like this instead of the global dataset. We can create a dictionary or function that maps country codes to URLs in a download.jl file. Looking forward to review a PR :+1: 

Closing this issue for now, good job!
